"""xp system

Revision ID: 42ec5d1d5af8
Revises: 216ecef1f6d7
Create Date: 2026-07-27 08:33:46.272858

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ec5d1d5af8'
down_revision: Union[str, None] = '216ecef1f6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seed values for the XP catalog. Add more later via PATCH /xp-actions/{key}
XP_ACTION_TYPES = [
    {"key": "basic_scan", "label": "Scanner un produit", "base_xp": 1},
    {"key": "vegandex_scan", "label": "Scanner un produit Vegandex", "base_xp": 5},
    {"key": "vegandex_scan_first_in_shop",
     "label": "Premier scan d'un produit vegandex dans ce magasin", "base_xp": 10},
    {"key": "shop_review", "label": "Noter un magasin", "base_xp": 15},
    {"key": "product_info_no_photo",
     "label": "Envoyer un produit (sans photo)", "base_xp": 10},
    {"key": "product_info_with_photo",
     "label": "Envoyer un produit (avec photo)", "base_xp": 20},
    {"key": "b12_intake", "label": "Prendre sa B12", "base_xp": 5},
    {"key": "error_report", "label": "Envoyer une info", "base_xp": 5},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    xp_action_types_table = op.create_table('xp_action_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('base_xp', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_action_types_id'), 'xp_action_types', ['id'], unique=False)
    op.create_index(op.f('ix_xp_action_types_key'), 'xp_action_types', ['key'], unique=True)

    seed_time = datetime.now()
    op.bulk_insert(
        xp_action_types_table,
        [
            {**row, "is_active": True, "created_at": seed_time}
            for row in XP_ACTION_TYPES
        ],
    )

    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['xp_action_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_action_type_id'), 'xp_events', ['action_type_id'], unique=False)
    op.create_index(op.f('ix_xp_events_created_at'), 'xp_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_events_id'), 'xp_events', ['id'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_created_at'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_action_type_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_xp_action_types_key'), table_name='xp_action_types')
    op.drop_index(op.f('ix_xp_action_types_id'), table_name='xp_action_types')
    op.drop_table('xp_action_types')
    # ### end Alembic commands ###
