"""avatar system

Revision ID: 63ca7315eb1d
Revises: 42ec5d1d5af8
Create Date: 2026-07-28 11:51:56.701502

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ca7315eb1d'
down_revision: Union[str, None] = '42ec5d1d5af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The original bundled avatars, free for everyone — seeded as
# is_default=True so they stay valid to equip and are excluded from
# jeton pulls (weight is unused for default avatars).
DEFAULT_AVATARS = [
    {"key": "canard.png", "label": "Canard"},
    {"key": "chat.png", "label": "Chat"},
    {"key": "cochon.png", "label": "Cochon"},
    {"key": "lapin.png", "label": "Lapin"},
    {"key": "mouton.png", "label": "Mouton"},
    {"key": "poisson.png", "label": "Poisson"},
    {"key": "poule.png", "label": "Poule"},
    {"key": "vache.png", "label": "Vache"},
    {"key": "ver.png", "label": "Ver"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    avatars_table = op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)
    op.create_index(op.f('ix_avatars_key'), 'avatars', ['key'], unique=True)
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'avatar_id', name='uq_user_avatar')
    )
    op.create_index(op.f('ix_user_avatars_avatar_id'), 'user_avatars', ['avatar_id'], unique=False)
    op.create_index(op.f('ix_user_avatars_id'), 'user_avatars', ['id'], unique=False)
    op.create_index(op.f('ix_user_avatars_user_id'), 'user_avatars', ['user_id'], unique=False)
    op.add_column('users', sa.Column('jetons', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping ix_scan_events_ean_shop_id
    # here — a false positive, since that index isn't declared in ORM
    # metadata (it's a raw op.create_index in the previous migration).
    # Left out intentionally; do not re-add it.

    seed_time = datetime.now()
    op.bulk_insert(
        avatars_table,
        [
            {
                **row,
                "weight": 0,
                "is_default": True,
                "is_active": True,
                "created_at": seed_time,
            }
            for row in DEFAULT_AVATARS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jetons')
    op.drop_index(op.f('ix_user_avatars_user_id'), table_name='user_avatars')
    op.drop_index(op.f('ix_user_avatars_id'), table_name='user_avatars')
    op.drop_index(op.f('ix_user_avatars_avatar_id'), table_name='user_avatars')
    op.drop_table('user_avatars')
    op.drop_index(op.f('ix_avatars_key'), table_name='avatars')
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.drop_table('avatars')
    # ### end Alembic commands ###
