"""partners ordering

Revision ID: b32cb864d000
Revises: 4e68f9a1447f
Create Date: 2026-08-09 15:02:02.937426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32cb864d000'
down_revision: Union[str, None] = '4e68f9a1447f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_categories', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('partners', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'display_order')
    op.drop_column('partner_categories', 'display_order')
    # ### end Alembic commands ###
