"""add validated to shops

Revision ID: b5e5d60043a7
Revises: 366bebfe896d
Create Date: 2026-09-13 08:24:09.667064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e5d60043a7'
down_revision: Union[str, None] = '366bebfe896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('validated', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_shops_validated'), 'shops', ['validated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_validated'), table_name='shops')
    op.drop_column('shops', 'validated')
    # ### end Alembic commands ###
