"""add date_deleted to shops

Revision ID: ffa4e2d172c7
Revises: b5e5d60043a7
Create Date: 2026-09-13 09:02:34.838730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa4e2d172c7'
down_revision: Union[str, None] = 'b5e5d60043a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('date_deleted', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_shops_date_deleted'), 'shops', ['date_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_date_deleted'), table_name='shops')
    op.drop_column('shops', 'date_deleted')
    # ### end Alembic commands ###
